### ISSUE TITLE
Can't access openvpn-as

### ISSUE THREAD

**Issue by king-anduin** [linuxserver/docker-openvpn-as#139]
hi guys,
I installed your docker version but I can't access it. I have a nginx proxy reverse server. 
**that's the docker ps**
![Screenshot from 2021-01-06 17-05-07](https://user-images.githubusercontent.com/56738872/103790629-beda3580-5041-11eb-8038-39d3480faf71.png)

**That's docker compose file**
```
version: "2.1"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - INTERFACE=eth0 #optional
    volumes:
      - /srv/openvpn:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194
    restart: unless-stopped
```
**That's my nginx reverse settings** 
```
upstream openvpn {
	server 0.0.0.0:943;
}

server {
	listen 80;
	listen [::]:80;
	
	server_name xx.com;
	
	# redirect to https
	return 301 xxx.com;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name xxx.com;

    access_log /var/log/nginx/openvpn.access.log;
    error_log /var/log/nginx/openvpn.error.log;

    ###****SSL settings for cloudflare****###
    ssl_certificate /srv/cloudlfare/cloudflare.crt;
    ssl_certificate_key /srv/cloudlfare/cloudflare.key;
    ssl_client_certificate /srv/cloudlfare/origin-pull-ca.pem;
    ssl_verify_client on;

    ###****SSL settings end for cloudflare****###

	location / {
	proxy_pass http://openvpn;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	}
}
```
**Thats my netstat where you can see it's listening**
![Screenshot from 2021-01-06 17-11-14](https://user-images.githubusercontent.com/56738872/103791042-445de580-5042-11eb-83c1-bb3dd161ce44.png)

I always get just Bad Gateway Error 502 when accessing it.
I hope you can help me out here.
