### ISSUE TITLE
Fresh install: unable to login through the webui admin. Default login/password give "Incorrect login." error message

### ISSUE THREAD

**Issue by JimyRyan** [linuxserver/docker-openvpn-as#33]
On a fresh usage of the Docker Hub "**linuxserver/openvpn-as**" (https://hub.docker.com/r/linuxserver/openvpn-as/), I can't access the admin webui located at the url **https://<ip>:943/admin**. I don't have any issue to access the web page, but when I use the default login/password (**admin/password**), I always got the error "**Incorrect login.**"

Bellow the openvpnas log after I try login to the OpenVPN administration interface:
```
2018-03-16 15:11:00+0100 [-] Server Agent started
2018-03-16 15:11:28+0100 [-] License Info {'apc': False, 'concurrent_connections': 2}
2018-03-16 15:12:10+0100 [-] WEB OUT: "2018-03-16 15:12:10+0100 [UDSProxyQueryProtocol,client] Web login authentication failed: {'status': 1, 'reason': 'PAM auth failed: System error', 'user': 'admin'}"
2018-03-16 15:12:10+0100 [-] WEB OUT: '2018-03-16 15:12:10+0100 [UDSProxyQueryProtocol,client] Web login failed (twisted.cred.error.UnauthorizedLogin)'
```

I'm using Docker image build number **114** 

It's strange, when I check the PAM faillures login using the command **pam_tally2 -u admin**, the failures counter show a nice **0**!
```
Login           Failures Latest failure     From
admin               0
```

More strange, the command **su - admin** give the fallowing error:  `su: System error`

I got something like previous error with the **passwd admin** command, bellow, the error log: 
```
Enter new UNIX password:
Retype new UNIX password:
passwd: System error
passwd: password unchanged
```

For more information, bellow, the trace of the **sudo docker info** command:
```
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /volume1/@docker/aufs
 Backing Filesystem: extfs
 Dirs: 575
 Dirperm1 Supported: true
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
Security Options:
 apparmor
Kernel Version: 3.10.102
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42GiB
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

To finish, some informations about docker-compose (command **sudo docker-compose version**):
```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Thank you for your help !

**Comment by sparklyballs** [comment]
i've just pulled a fresh image and can login no issues with user admin and password password

**Comment by JimyRyan** [comment]
I don't understand... Here is my docker-compose file:
```
version: "2.2"
services:
    openvpnas:
        image: linuxserver/openvpn-as:latest
        restart: always
        container_name: shared-openvpnas
        mem_limit: 1G
        memswap_limit: 0
        mem_reservation: 512M
        privileged: true
        env_file:
            - ./global.env
        network_mode: host
        volumes:
            - /...:/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /...:/config
```

And the ./global.env file:
```
PGID=XXX
PUID=XXX
TZ=Europe/Paris
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
```

I don't know the is wrong...
