### ISSUE TITLE
Error: Could not execute server start

### ISSUE THREAD

**Issue by mario26** [linuxserver/docker-openvpn-as#66]
Hi!

I can not run the server anymore:
```
openvpn-as      | Starting openvpnas...
openvpn-as      | Error: Could not execute server start.
```
Here is my docker-compose.yml:
```
     openvpn-as:
        image: linuxserver/openvpn-as
        #restart: ${RESTART_MODE}
        container_name: openvpn-as 
        volumes:
                - ${VOLUMES_ROOT_PATH}/config/openvpn:/config
        ports:
                - "1194:1194/udp"
                - "9443:9443/tcp"
                - "943:943"
        cap_add:
                - NET_ADMIN
        environment:
                - PGID=1000
                - PUID=1000
                - TZ=Europe/Paris
```

When configuring the port i have this:
```
openvpn-as      | Please enter the option number from the list above (1-2).
openvpn-as      | > Press Enter for default [2]: 
openvpn-as      | Please specify the port number for the Admin Web UI.
openvpn-as      | > Press ENTER for default [943]: 
openvpn-as      | Please specify the TCP port number for the OpenVPN Daemon
openvpn-as      | > Press ENTER for default [443]: 
openvpn-as      | Should client traffic be routed by default through the VPN?
openvpn-as      | > Press ENTER for default [yes]: 
openvpn-as      | Should client DNS traffic be routed by default through the VPN?
openvpn-as      | > Press ENTER for default [yes]: 
openvpn-as      | Use local authentication via internal DB?
openvpn-as      | > Press ENTER for default [yes]: 
```
I see port 443, why is this port configured? I have a Nginx server running on port 443, will it be a conflict?

I did not change anything, at first it worked, but now I have this:

```
openvpn-as      | [cont-init.d] 10-adduser: exited 0.
openvpn-as      | [cont-init.d] 20-time: executing... 
openvpn-as      | [cont-init.d] 20-time: exited 0.
openvpn-as      | [cont-init.d] 30-config: executing... 
openvpn-as      | [cont-init.d] 30-config: exited 0.
openvpn-as      | [cont-init.d] 40-openvpn-init: executing... 
openvpn-as      | [cont-init.d] 40-openvpn-init: exited 0.
openvpn-as      | [cont-init.d] 50-interface: executing... 
openvpn-as      | MOD Default {} {}
openvpn-as      | MOD Default {} {}
openvpn-as      | MOD Default {} {}
openvpn-as      | MOD Default {} {}
openvpn-as      | [cont-init.d] 50-interface: exited 0.
openvpn-as      | [cont-init.d] done
```
I to empty the configuration, start from the beginning, but it does not work anymore, i do not understand what is happening, can you help me?

Thank you
