### ISSUE TITLE
Configuring the server via cli

### ISSUE THREAD

**Issue by mario26** [linuxserver/docker-openvpn-as#67]
Hi!

@j0nnymoe explains that i am trying to configure openvpn via the cli, but i do not do of it...

The problem came suddenly last night without any modification on my part, i opened a issue here: https://github.com/linuxserver/docker-openvpn-as/issues/66

I found a similar problem related to the ports here: https://github.com/linuxserver/docker-openvpn-as/issues/50

However, i have indicated the ports in my docker-compose.yml but it does not work anymore and i do not understand the reason ?!

```
     openvpn-as:
        image: linuxserver/openvpn-as
        #restart: ${RESTART_MODE}
        container_name: openvpn-as 
        volumes:
                - ${VOLUMES_ROOT_PATH}/config/openvpn:/config
        ports:
                - "1194:1194/udp"
                - "9443:9443"
                - "943:943"
        cap_add:
                - NET_ADMIN
        environment:
                - PGID=1000
                - PUID=1000
                - TZ=Europe/Paris
```

I followed the documentation, nothing more, yesterday it worked very well, today it does not work anymore...

I emptied the directory "/config" to resume the installation at the beginning, but the perssist problem.

Can you help me understand the problem before closing the issue?

Thank you
