### ISSUE TITLE
Anyone tried this with L2 (bridging/TAP) mode? Doesn't work

### ISSUE THREAD

**Issue by melikyuksel** [linuxserver/docker-openvpn-as#72]
Just looking for some tips on how to get this working in TAP mode with bridging. If I switch it to L2 mode as per AS documentation, I can connect to the server, but I can't reach the server's gateway or any other devices. By default, the client's TAP interface doesn't receive a DHCP address but even assigning a static one doesn't change anything.

Running Debian 9. The docker-compose here:
```
tap-test:
    image: linuxserver/openvpn-as
    container_name: tap-test
    restart: unless-stopped
    privileged: true
    cap_add:
      - ALL
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/mike/tap-test:/config
    ports:
      - 943:943
      - 1194:1194/udp
```

When the TAP AS container comes up, this device shows up on the docker host:
```
123: vethaa198f2@if122: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-11c00b298643 state UP group default 
    link/ether 22:31:b1:b4:cb:2e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::2031:b1ff:feb4:cb2e/64 scope link 
       valid_lft forever preferred_lft forever
```
