### ISSUE TITLE
When reaching the openVPN's gui, I am getting: "Your connection is not private"

### ISSUE THREAD

**Issue by tal47** [linuxserver/docker-openvpn-as#78]
Hi,
I have exported my OpenVPN docker and it works well (thank you for that)
The issue is when reaching that ip+port (https://< ip >:943/) where my VPN server is, I am getting as shown in the image below.

![image](https://user-images.githubusercontent.com/16876322/56581458-aad87100-65dd-11e9-8cec-8a628771a629.png)

I am suspecting SSL server configs in the container, by now I can see a difference in the timezone - The logfiles time is 4 hours difference - although I have set TZ in the docker-compose file.
How can I solve that issue?
Thanks!

###Host OS
Fedora 28

docker-compose.yml:
```
version: '3'
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as-compose 
    restart: always
    volumes:
      - ./openvpn-data/:/config
    network_mode: "host"  (I know it's not good, will fix that soon)
    privileged: true  (I know it's not good, will fix that soon)
    environment:
     - PGID=950800023
     - PUID=1009
     - TZ=IL 
     - INTERFACE=enp0s2 
```

Nothing helpful in docker log.

Thanks.
