### ISSUE TITLE
Container must be restarted when launching from docker-compose

### ISSUE THREAD

**Issue by ingenieurmt** [linuxserver/docker-openvpn-as#83]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: RancherOS v1.5.3

```
  openvpn:
    container_name: openvpn
    hostname: vpn
    domainname: example.com
    image: "linuxserver/openvpn-as:latest"
    restart: always
    ports:
      - "943:943"
      - "9443:9443"
      - "1194:1194/udp"
    environment:
      - PUID=1100
      - PGID=1101
      - TZ=Somewhere/Sometime
    volumes:
      - type: volume
        source: openvpn_data
        target: /config
    cap_add:
      - NET_ADMIN
    networks:
      - examplenet
```

When spinning up an OpenVPN instance in Docker using the above docker-compose, I get a lot of strange errors such as `CPage error in CLogin/locateChild` when trying to visit the web interface. Running `docker container restart openvpn` fixes this. I suspect there is a bug in the startup scripts that are part of the Docker image.
