### ISSUE TITLE
Fix pam authentication issues with network mode host

### ISSUE THREAD

**Issue by doino-gretchenliev** [linuxserver/docker-openvpn-as#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

When the image is started with network mode host the web ui fails to authenticate with the pam module.

------------------------------

## Expected Behavior
It should authenticate as the container started with a bridge network.

## Steps to Reproduce
1. Docker compose setup:
```
version: "3"
services:
  openvpn:
    image: linuxserver/openvpn-as:latest
    container_name: openvpn
    volumes:
      - /docker/openvpn/config:/config:rw
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 1194:1194/udp
      - 943:943
      - 9443:9443
    network_mode: host
    environment:
      - PGID=999
      - PUID=999
      - TZ=Europe/Sofia
    privileged: true
```

## Environment
Linux 3.10.105 SMP Tue Jul 3 19:50:10 CST 2018 x86_64 GNU/Linux synology_broadwell_3617xs

## The fix
Rebuild pam module without audit:
```
RUN apt-get update && \
    apt-get -y build-dep pam && \
    export CONFIGURE_OPTS=--disable-audit && \
    cd /tmp && \
    apt-get -b source pam && \
    dpkg -i libpam-doc*.deb libpam-modules*.deb libpam-runtime*.deb libpam0g*.deb && \
    rm -rf /tmp/*
```
