### ISSUE TITLE
Unable to reach other Docker services

### ISSUE THREAD

**Issue by DenBeke** [linuxserver/docker-openvpn-as#98]
## Expected Behavior

I have a docker-compose with:
- openvpn (with `network: host` option)
- another service exposed on port 8888 in a regular bridged docker network.

VPN clients can connect to other services on the host. But only to service that are not ran with Docker, or Docker services that are ran using `network: host` option.

VPN clients cannot connect to docker containers that are NOT ran with `network: host` option. (So the above service with port 8888 is not reachable)

## Current Behavior

Got timeouts on the docker service on port 8888.

## Steps to Reproduce

Create a new docker-compose file with openvpn-as in with host networking enabled. And another service with ports forwarded without any network specified for it.

I followed the approach suggested here to make the host network reachable: https://github.com/linuxserver/docker-openvpn-as/issues/96

## Environment
**OS:**  Ubuntu 18.04
**CPU architecture:** x86_64 
**How docker service was installed:** https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by aptalca** [comment]
You likely changed too much in gui settings. Follow my post in that other thread. There is no reason for you to run this with host networking.

Closing this because it is not a bug, but user settings issue

**Comment by DenBeke** [comment]
> You likely changed too much in gui settings. Follow my post in that other thread. There is no reason for you to run this with host networking.

So with NAT and without host networking I can access other devices in the hosts network without any problems?

**Comment by aptalca** [comment]
yes

**Comment by DenBeke** [comment]
Thank you for helping out here. Majority seems to work now, but I still can't access other docker services that don't have the `network: host` set.


With the following config I can access other nodes in the local network by using the local IP address: `192.168.0.x`. I can access Plex on the host machine with the local IP of the host machine: `192.168.0.y`. But I cannot access Caddy with the local IP of the host machine.

```
--- 
version: "3.4"
services: 
  openvpn:
    container_name: openvpn
    image: linuxserver/openvpn-as
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/openvpn:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped

  plex:
    container_name: plex
    image: linuxserver/plex
    network_mode: host

  caddy:
    container_name: caddy
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
```

Am I missing some docker/networking fundamentals here? Because I can access the Caddy from within another container using the host IP. Just not from my VPN.
